import { StyleSheet } from "react-native";

import {
  FontWeight,
  Radius,
  Spacing,
  TypeScale,
  shadow,
} from "../../constants/design-system";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#F0F0F0",
    flex: 1,
  },
  loader: {
    alignItems: "center",
    backgroundColor: "#F0F0F0",
    flex: 1,
    justifyContent: "center",
  },
  header: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderBottomColor: "#E8E8E8",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  headerMainPressable: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: Radius.lg,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  headerAvatar: {
    marginLeft: Spacing.md,
  },
  headerAvatarImage: {
    borderRadius: Radius.xl,
    height: 44,
    width: 44,
  },
  headerAvatarCircle: {
    alignItems: "center",
    borderRadius: Radius.xl,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  headerAvatarText: {
    color: "#FFFFFF",
    ...TypeScale.titleLg,
    fontWeight: FontWeight.extrabold,
  },
  headerTextWrap: {
    flex: 1,
    marginLeft: Spacing.md,
  },
  headerTitle: {
    color: "#1A1A1A",
    ...TypeScale.titleLg,
    fontWeight: FontWeight.extrabold,
    flexShrink: 1,
  },
  headerMeta: {
    color: "#6B7280",
    ...TypeScale.bodySm,
    marginTop: Spacing.xs,
    flexShrink: 1,
  },
  detailsScreen: {
    flex: 1,
  },
  detailsTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
  },
  detailsTopBarTitle: {
    ...TypeScale.titleMd,
    fontWeight: FontWeight.bold,
  },
  groupDetailsContent: {
    paddingBottom: Spacing["4xl"],
  },
  detailsHeroSection: {
    alignItems: "center",
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.lg,
  },
  detailsSection: {
    borderRadius: Radius.xl,
    borderWidth: 1,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.md,
    padding: Spacing.lg,
  },
  detailsSectionTitle: {
    ...TypeScale.labelLg,
    fontWeight: FontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: Spacing.sm,
  },
  groupDetailsPhotoWrap: {
    position: "relative",
    marginBottom: Spacing.md,
  },
  groupDetailsPhoto: {
    borderRadius: Radius.xl,
    height: 80,
    width: 80,
  },
  groupDetailsPhotoFallback: {
    alignItems: "center",
    borderRadius: Radius.xl,
    height: 80,
    justifyContent: "center",
    width: 80,
  },
  groupDetailsPhotoFallbackText: {
    color: "#FFFFFF",
    ...TypeScale.headingLg,
    fontWeight: FontWeight.extrabold,
  },
  groupDetailsPhotoBadge: {
    alignItems: "center",
    backgroundColor: "#FFF2DA",
    borderColor: "#E8E8E8",
    borderRadius: Radius.full,
    borderWidth: 1,
    bottom: Spacing.xs,
    height: 30,
    justifyContent: "center",
    position: "absolute",
    right: Spacing.xs,
    width: 30,
  },
  detailsHeroTitle: {
    ...TypeScale.headingLg,
    fontWeight: FontWeight.extrabold,
    textAlign: "center",
    marginBottom: Spacing.xs,
  },
  detailsHeroMeta: {
    ...TypeScale.bodyMd,
    textAlign: "center",
  },
  groupDetailsSecondaryAction: {
    alignSelf: "center",
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
  },
  groupDetailsSecondaryActionText: {
    ...TypeScale.bodySm,
    fontWeight: FontWeight.semibold,
  },
  descriptionCard: {
    backgroundColor: "#FFF8E7",
    borderColor: "#F1D7A5",
    borderRadius: Radius.lg,
    borderWidth: 1,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.md,
    padding: Spacing.md,
  },
  descriptionText: {
    color: "#5A6E41",
    ...TypeScale.bodyMd,
  },
  membersHeaderRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: Spacing.md,
  },
  membersSearchShell: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E8E8E8",
    borderRadius: Radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    marginBottom: 2,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  membersSearchInput: {
    color: "#1A1A1A",
    flex: 1,
    ...TypeScale.bodyMd,
    marginLeft: Spacing.sm,
    paddingVertical: 0,
  },
  membersSubtitle: {
    color: "#6B7280",
    ...TypeScale.bodySm,
    marginTop: Spacing.xs,
  },
  membersCountBadge: {
    backgroundColor: "#F5F5F5",
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  membersCountText: {
    color: "#6B7280",
    ...TypeScale.labelLg,
    fontWeight: FontWeight.extrabold,
  },
  membersEmptyText: {
    color: "#6B7C5D",
    ...TypeScale.bodySm,
    marginTop: Spacing.md,
  },
  memberRow: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: Spacing.sm,
  },
  memberAvatarCircle: {
    alignItems: "center",
    backgroundColor: "#2D6A4F",
    borderRadius: Radius.full,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  memberAvatarImage: {
    borderRadius: Radius.full,
    height: 42,
    width: 42,
  },
  memberAvatarText: {
    color: "#FFFFFF",
    ...TypeScale.bodyMd,
    fontWeight: FontWeight.extrabold,
  },
  memberTextWrap: {
    flex: 1,
    marginLeft: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  memberName: {
    color: "#1A1A1A",
    ...TypeScale.bodyMd,
    fontWeight: FontWeight.extrabold,
    flexShrink: 1,
  },
  memberMeta: {
    color: "#6B7A5D",
    ...TypeScale.labelMd,
    marginTop: Spacing.xs,
  },
  memberActionButton: {
    backgroundColor: "#FFF1EF",
    borderColor: "#F0C7C1",
    borderRadius: Radius.md,
    borderWidth: 1,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  memberActionButtonDisabled: {
    opacity: 0.6,
  },
  memberActionButtonText: {
    color: "#8A3D35",
    ...TypeScale.labelLg,
    fontWeight: FontWeight.extrabold,
  },
  settingsSubtitle: {
    color: "#6B7280",
    ...TypeScale.bodySm,
    marginBottom: Spacing.md,
    marginTop: Spacing.xs,
  },
  settingsLabel: {
    color: "#6B7280",
    ...TypeScale.labelLg,
    fontWeight: FontWeight.extrabold,
    marginBottom: Spacing.sm,
    marginTop: Spacing.sm,
    textTransform: "uppercase",
  },
  settingsInput: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E8E8E8",
    borderRadius: Radius.lg,
    borderWidth: 1,
    color: "#1A1A1A",
    ...TypeScale.bodyMd,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
  },
  groupDescriptionInput: {
    minHeight: 100,
  },
  settingsSaveButton: {
    alignItems: "center",
    backgroundColor: "#2D6A4F",
    borderRadius: Radius.lg,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  settingsSaveButtonDisabled: {
    opacity: 0.6,
  },
  settingsSaveButtonText: {
    color: "#FFFFFF",
    ...TypeScale.bodyMd,
    fontWeight: FontWeight.extrabold,
  },
  joinInfoCard: {
    alignItems: "center",
    backgroundColor: "#F8F8F8",
    borderColor: "#E8E8E8",
    borderRadius: Radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.md,
    padding: Spacing.md,
  },
  joinInfoTextWrap: {
    flex: 1,
    paddingRight: Spacing.md,
  },
  joinInfoTitle: {
    color: "#1A1A1A",
    ...TypeScale.titleSm,
    fontWeight: FontWeight.extrabold,
    marginBottom: Spacing.xs,
  },
  joinInfoText: {
    color: "#6B7280",
    ...TypeScale.bodySm,
  },
  joinInfoButton: {
    alignItems: "center",
    backgroundColor: "#2D6A4F",
    borderRadius: Radius.md,
    justifyContent: "center",
    minWidth: 104,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  joinInfoButtonDisabled: {
    opacity: 0.6,
  },
  joinInfoButtonText: {
    color: "#FFFFFF",
    ...TypeScale.bodySm,
    fontWeight: FontWeight.extrabold,
  },
  toastContainer: {
    position: "absolute",
    bottom: 100,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 50,
  },
  toast: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: Radius.xl,
    borderWidth: 1,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    marginHorizontal: Spacing.lg,
    maxWidth: 420,
    ...shadow("lg"),
  },
  toastText: {
    ...TypeScale.bodySm,
    fontWeight: FontWeight.semibold,
    flex: 1,
    marginHorizontal: Spacing.sm,
  },
  expenseSummaryCard: {
    borderRadius: Radius.xl,
    borderWidth: 1,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.md,
    padding: Spacing.lg,
  },
  expenseSummaryHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  expenseSummaryHeaderTextWrap: {
    flex: 1,
    paddingRight: Spacing.md,
  },
  expenseSummaryKicker: {
    ...TypeScale.labelLg,
    fontWeight: FontWeight.extrabold,
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  expenseSummaryTitle: {
    ...TypeScale.headingLg,
    fontWeight: FontWeight.extrabold,
    marginTop: Spacing.xs,
  },
  expenseSummaryText: {
    ...TypeScale.bodyMd,
    marginTop: Spacing.sm,
  },
  expenseSummaryCountBadge: {
    borderRadius: Radius.full,
    borderWidth: 1,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  expenseSummaryCountText: {
    ...TypeScale.labelLg,
    fontWeight: FontWeight.extrabold,
  },
  expenseSummaryChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  expenseSummaryChip: {
    alignItems: "center",
    borderRadius: Radius.full,
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  expenseSummaryChipText: {
    ...TypeScale.labelLg,
    fontWeight: FontWeight.bold,
  },
  messagesScroll: {
    flex: 1,
    marginTop: Spacing.sm,
  },
  messagesContent: {
    paddingBottom: Spacing.xl,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: "#F8F8F8",
    borderColor: "#E8E8E8",
    borderRadius: Radius["2xl"],
    borderWidth: 1,
    marginTop: Spacing.lg,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing["3xl"],
  },
  emptyTitle: {
    color: "#1A1A1A",
    ...TypeScale.headingSm,
    fontWeight: FontWeight.extrabold,
    textAlign: "center",
  },
  emptyText: {
    color: "#6B7280",
    ...TypeScale.bodyMd,
    marginTop: Spacing.sm,
    textAlign: "center",
  },
  modalOverlay: {
    backgroundColor: "rgba(19, 29, 11, 0.26)",
    flex: 1,
    justifyContent: "flex-end",
    padding: Spacing.lg,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetCard: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E8E8E8",
    borderRadius: Radius["3xl"],
    borderWidth: 1,
    maxHeight: "76%",
    padding: Spacing.lg,
  },
  sheetHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: Spacing.md,
  },
  sheetHeaderTextWrap: {
    flex: 1,
    paddingRight: Spacing.md,
  },
  sheetTitle: {
    color: "#1A1A1A",
    ...TypeScale.headingSm,
    fontWeight: FontWeight.extrabold,
  },
  sheetSubtitle: {
    color: "#6B7280",
    ...TypeScale.bodyMd,
    marginTop: Spacing.xs,
  },
  sheetCloseButton: {
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: Radius.md,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  sheetEmptyState: {
    alignItems: "center",
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xl,
  },
  sheetEmptyTitle: {
    color: "#1A1A1A",
    ...TypeScale.titleLg,
    fontWeight: FontWeight.extrabold,
    textAlign: "center",
  },
  sheetEmptyText: {
    color: "#6B7280",
    ...TypeScale.bodyMd,
    marginTop: Spacing.sm,
    textAlign: "center",
  },
  sheetPrimaryButton: {
    alignItems: "center",
    backgroundColor: "#2D6A4F",
    borderRadius: Radius.lg,
    marginTop: Spacing.lg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  sheetPrimaryButtonText: {
    color: "#FFFFFF",
    ...TypeScale.bodyMd,
    fontWeight: FontWeight.extrabold,
  },
  sheetTextInput: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E8E8E8",
    borderRadius: Radius.lg,
    borderWidth: 1,
    color: "#1A1A1A",
    ...TypeScale.titleSm,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
  },
  sheetTripsContent: {
    paddingBottom: Spacing.xs,
  },
  sheetTripCard: {
    backgroundColor: "#F8F8F8",
    borderColor: "#E8E8E8",
    borderRadius: Radius.xl,
    borderWidth: 1,
    marginBottom: Spacing.md,
    padding: Spacing.lg,
  },
  sheetTripTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: Spacing.sm,
  },
  sheetTripSourceBadge: {
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  sheetTripSourceBadgeText: {
    ...TypeScale.labelSm,
    fontWeight: FontWeight.extrabold,
  },
  sharedTripHomeBadge: {
    backgroundColor: "#E5E7EB",
  },
  sharedTripDiscoverBadge: {
    backgroundColor: "#FFF2DA",
  },
  sharedTripHomeBadgeText: {
    color: "#2D6A4F",
  },
  sharedTripDiscoverBadgeText: {
    color: "#8B5611",
  },
  sheetTripDate: {
    color: "#6B7A5D",
    ...TypeScale.labelMd,
    fontWeight: FontWeight.bold,
  },
  sheetTripTitle: {
    color: "#1A1A1A",
    ...TypeScale.titleLg,
    fontWeight: FontWeight.extrabold,
  },
  sheetTripDestination: {
    color: "#5A6E41",
    ...TypeScale.bodyMd,
    fontWeight: FontWeight.bold,
    marginTop: Spacing.xs,
  },
  sheetTripMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: Spacing.sm,
  },
  sheetTripMetaText: {
    color: "#627254",
    ...TypeScale.bodySm,
    fontWeight: FontWeight.bold,
    marginBottom: Spacing.xs,
    marginRight: Spacing.sm,
  },
  sheetTripSummary: {
    color: "#4C5D3F",
    ...TypeScale.bodySm,
    marginTop: Spacing.sm,
  },
  sheetShareButton: {
    alignItems: "center",
    backgroundColor: "#2D6A4F",
    borderRadius: Radius.md,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  sheetShareButtonDisabled: {
    opacity: 0.6,
  },
  sheetShareButtonText: {
    color: "#FFFFFF",
    ...TypeScale.bodySm,
    fontWeight: FontWeight.extrabold,
  },
  previewCard: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E8E8E8",
    borderRadius: Radius["3xl"],
    borderWidth: 1,
    marginBottom: Spacing.lg,
    maxHeight: "82%",
    padding: Spacing.lg,
  },
  previewHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  previewHeaderTextWrap: {
    flex: 1,
    paddingRight: Spacing.md,
  },
  previewTitle: {
    color: "#1A1A1A",
    ...TypeScale.headingMd,
    fontWeight: FontWeight.extrabold,
  },
  previewDestination: {
    color: "#5A6E41",
    ...TypeScale.bodyMd,
    fontWeight: FontWeight.bold,
    marginTop: Spacing.xs,
  },
  previewMetaRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: Spacing.md,
  },
  previewMetaText: {
    color: "#627254",
    ...TypeScale.bodySm,
    fontWeight: FontWeight.bold,
    marginBottom: Spacing.xs,
    marginLeft: Spacing.sm,
  },
  previewSummary: {
    color: "#435238",
    ...TypeScale.bodyMd,
    marginTop: Spacing.md,
  },
  previewLinkedTransportSection: {
    marginTop: Spacing.lg,
  },
  previewLinkedTransportTitle: {
    color: "#6B7280",
    ...TypeScale.bodySm,
    fontWeight: FontWeight.extrabold,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  previewLinkedTransportCard: {
    backgroundColor: "#F8F8F8",
    borderColor: "#E8E8E8",
    borderRadius: Radius.lg,
    borderWidth: 1,
    marginTop: Spacing.sm,
    padding: Spacing.md,
  },
  previewLinkedTransportTopRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  previewLinkedTransportTextWrap: {
    flex: 1,
    paddingRight: Spacing.sm,
  },
  previewLinkedTransportCardTitle: {
    color: "#1A1A1A",
    ...TypeScale.titleSm,
    fontWeight: FontWeight.extrabold,
  },
  previewLinkedTransportRoute: {
    color: "#5A6E41",
    ...TypeScale.bodySm,
    marginTop: Spacing.xs,
  },
  previewLinkedTransportAmount: {
    color: "#1A1A1A",
    ...TypeScale.bodyMd,
    fontWeight: FontWeight.extrabold,
  },
  previewLinkedTransportMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  previewLinkedTransportMetaText: {
    color: "#627254",
    ...TypeScale.labelMd,
    fontWeight: FontWeight.bold,
  },
  previewLinkedTransportButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#F5F5F5",
    borderColor: "#E8E8E8",
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.xs,
    justifyContent: "center",
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  previewLinkedTransportButtonText: {
    color: "#6B7280",
    ...TypeScale.labelLg,
    fontWeight: FontWeight.extrabold,
  },
  previewDetailsScroll: {
    marginTop: Spacing.md,
  },
  previewDetailsContent: {
    paddingBottom: Spacing.xs,
  },
  previewDetailsText: {
    color: "#46563A",
    ...TypeScale.bodyMd,
  },
  expensePreviewCard: {
    backgroundColor: "#F8F8F8",
    borderColor: "#E8E8E8",
    borderRadius: Radius.xl,
    borderWidth: 1,
    marginTop: Spacing.lg,
    padding: Spacing.lg,
  },
  expensePreviewKicker: {
    color: "#2D6A4F",
    ...TypeScale.labelLg,
    fontWeight: FontWeight.extrabold,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  expensePreviewTitle: {
    color: "#1A1A1A",
    ...TypeScale.headingSm,
    fontWeight: FontWeight.extrabold,
    marginTop: Spacing.xs,
  },
  expensePreviewMeta: {
    color: "#5A6E41",
    ...TypeScale.bodyMd,
    marginTop: Spacing.sm,
  },
  expensePreviewPills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  expensePreviewPill: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E8E8E8",
    borderRadius: Radius.full,
    borderWidth: 1,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  expensePreviewPillText: {
    color: "#4E6630",
    ...TypeScale.labelLg,
    fontWeight: FontWeight.bold,
  },
  previewSaveButton: {
    alignItems: "center",
    backgroundColor: "#2D6A4F",
    borderRadius: Radius.lg,
    marginTop: Spacing.lg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  previewSaveButtonDisabled: {
    opacity: 0.6,
  },
  previewSaveButtonText: {
    color: "#FFFFFF",
    ...TypeScale.bodyMd,
    fontWeight: FontWeight.extrabold,
  },
});
