import type { AppLanguage } from "./translations";

export type Country = {
  code: string;
  name: Record<AppLanguage, string>;
};

export const COUNTRIES: Country[] = [
  { code: "AF", name: { bg: "Афганистан", en: "Afghanistan", de: "Afghanistan", es: "Afganistán", fr: "Afghanistan" } },
  { code: "AL", name: { bg: "Албания", en: "Albania", de: "Albanien", es: "Albania", fr: "Albanie" } },
  { code: "DZ", name: { bg: "Алжир", en: "Algeria", de: "Algerien", es: "Argelia", fr: "Algérie" } },
  { code: "AD", name: { bg: "Андора", en: "Andorra", de: "Andorra", es: "Andorra", fr: "Andorre" } },
  { code: "AO", name: { bg: "Ангола", en: "Angola", de: "Angola", es: "Angola", fr: "Angola" } },
  { code: "AG", name: { bg: "Антигуа и Барбуда", en: "Antigua and Barbuda", de: "Antigua und Barbuda", es: "Antigua y Barbuda", fr: "Antigua-et-Barbuda" } },
  { code: "AR", name: { bg: "Аржентина", en: "Argentina", de: "Argentinien", es: "Argentina", fr: "Argentine" } },
  { code: "AM", name: { bg: "Армения", en: "Armenia", de: "Armenien", es: "Armenia", fr: "Arménie" } },
  { code: "AU", name: { bg: "Австралия", en: "Australia", de: "Australien", es: "Australia", fr: "Australie" } },
  { code: "AT", name: { bg: "Австрия", en: "Austria", de: "Österreich", es: "Austria", fr: "Autriche" } },
  { code: "AZ", name: { bg: "Азербайджан", en: "Azerbaijan", de: "Aserbaidschan", es: "Azerbaiyán", fr: "Azerbaïdjan" } },
  { code: "BS", name: { bg: "Бахамски острови", en: "Bahamas", de: "Bahamas", es: "Bahamas", fr: "Bahamas" } },
  { code: "BH", name: { bg: "Бахрейн", en: "Bahrain", de: "Bahrain", es: "Baréin", fr: "Bahreïn" } },
  { code: "BD", name: { bg: "Бангладеш", en: "Bangladesh", de: "Bangladesch", es: "Bangladés", fr: "Bangladesh" } },
  { code: "BB", name: { bg: "Барбадос", en: "Barbados", de: "Barbados", es: "Barbados", fr: "Barbade" } },
  { code: "BY", name: { bg: "Беларус", en: "Belarus", de: "Belarus", es: "Bielorrusia", fr: "Biélorussie" } },
  { code: "BE", name: { bg: "Белгия", en: "Belgium", de: "Belgien", es: "Bélgica", fr: "Belgique" } },
  { code: "BZ", name: { bg: "Белиз", en: "Belize", de: "Belize", es: "Belice", fr: "Belize" } },
  { code: "BJ", name: { bg: "Бенин", en: "Benin", de: "Benin", es: "Benín", fr: "Bénin" } },
  { code: "BT", name: { bg: "Бутан", en: "Bhutan", de: "Bhutan", es: "Bután", fr: "Bhoutan" } },
  { code: "BO", name: { bg: "Боливия", en: "Bolivia", de: "Bolivien", es: "Bolivia", fr: "Bolivie" } },
  { code: "BA", name: { bg: "Босна и Херцеговина", en: "Bosnia and Herzegovina", de: "Bosnien und Herzegowina", es: "Bosnia y Herzegovina", fr: "Bosnie-Herzégovine" } },
  { code: "BW", name: { bg: "Ботсвана", en: "Botswana", de: "Botswana", es: "Botsuana", fr: "Botswana" } },
  { code: "BR", name: { bg: "Бразилия", en: "Brazil", de: "Brasilien", es: "Brasil", fr: "Brésil" } },
  { code: "BN", name: { bg: "Бруней", en: "Brunei", de: "Brunei", es: "Brunéi", fr: "Brunei" } },
  { code: "BG", name: { bg: "България", en: "Bulgaria", de: "Bulgarien", es: "Bulgaria", fr: "Bulgarie" } },
  { code: "BF", name: { bg: "Буркина Фасо", en: "Burkina Faso", de: "Burkina Faso", es: "Burkina Faso", fr: "Burkina Faso" } },
  { code: "BI", name: { bg: "Бурунди", en: "Burundi", de: "Burundi", es: "Burundi", fr: "Burundi" } },
  { code: "KH", name: { bg: "Камбоджа", en: "Cambodia", de: "Kambodscha", es: "Camboya", fr: "Cambodge" } },
  { code: "CM", name: { bg: "Камерун", en: "Cameroon", de: "Kamerun", es: "Camerún", fr: "Cameroun" } },
  { code: "CA", name: { bg: "Канада", en: "Canada", de: "Kanada", es: "Canadá", fr: "Canada" } },
  { code: "CL", name: { bg: "Чили", en: "Chile", de: "Chile", es: "Chile", fr: "Chili" } },
  { code: "CN", name: { bg: "Китай", en: "China", de: "China", es: "China", fr: "Chine" } },
  { code: "CO", name: { bg: "Колумбия", en: "Colombia", de: "Kolumbien", es: "Colombia", fr: "Colombie" } },
  { code: "CR", name: { bg: "Коста Рика", en: "Costa Rica", de: "Costa Rica", es: "Costa Rica", fr: "Costa Rica" } },
  { code: "HR", name: { bg: "Хърватия", en: "Croatia", de: "Kroatien", es: "Croacia", fr: "Croatie" } },
  { code: "CU", name: { bg: "Куба", en: "Cuba", de: "Kuba", es: "Cuba", fr: "Cuba" } },
  { code: "CY", name: { bg: "Кипър", en: "Cyprus", de: "Zypern", es: "Chipre", fr: "Chypre" } },
  { code: "CZ", name: { bg: "Чехия", en: "Czech Republic", de: "Tschechien", es: "Chequia", fr: "Tchéquie" } },
  { code: "DK", name: { bg: "Дания", en: "Denmark", de: "Dänemark", es: "Dinamarca", fr: "Danemark" } },
  { code: "DO", name: { bg: "Доминиканска република", en: "Dominican Republic", de: "Dominikanische Republik", es: "República Dominicana", fr: "République dominicaine" } },
  { code: "EC", name: { bg: "Еквадор", en: "Ecuador", de: "Ecuador", es: "Ecuador", fr: "Équateur" } },
  { code: "EG", name: { bg: "Египет", en: "Egypt", de: "Ägypten", es: "Egipto", fr: "Égypte" } },
  { code: "SV", name: { bg: "Ел Салвадор", en: "El Salvador", de: "El Salvador", es: "El Salvador", fr: "Salvador" } },
  { code: "EE", name: { bg: "Естония", en: "Estonia", de: "Estland", es: "Estonia", fr: "Estonie" } },
  { code: "ET", name: { bg: "Етиопия", en: "Ethiopia", de: "Äthiopien", es: "Etiopía", fr: "Éthiopie" } },
  { code: "FI", name: { bg: "Финландия", en: "Finland", de: "Finnland", es: "Finlandia", fr: "Finlande" } },
  { code: "FR", name: { bg: "Франция", en: "France", de: "Frankreich", es: "Francia", fr: "France" } },
  { code: "GE", name: { bg: "Грузия", en: "Georgia", de: "Georgien", es: "Georgia", fr: "Géorgie" } },
  { code: "DE", name: { bg: "Германия", en: "Germany", de: "Deutschland", es: "Alemania", fr: "Allemagne" } },
  { code: "GH", name: { bg: "Гана", en: "Ghana", de: "Ghana", es: "Ghana", fr: "Ghana" } },
  { code: "GR", name: { bg: "Гърция", en: "Greece", de: "Griechenland", es: "Grecia", fr: "Grèce" } },
  { code: "GT", name: { bg: "Гватемала", en: "Guatemala", de: "Guatemala", es: "Guatemala", fr: "Guatemala" } },
  { code: "HN", name: { bg: "Хондурас", en: "Honduras", de: "Honduras", es: "Honduras", fr: "Honduras" } },
  { code: "HU", name: { bg: "Унгария", en: "Hungary", de: "Ungarn", es: "Hungría", fr: "Hongrie" } },
  { code: "IS", name: { bg: "Исландия", en: "Iceland", de: "Island", es: "Islandia", fr: "Islande" } },
  { code: "IN", name: { bg: "Индия", en: "India", de: "Indien", es: "India", fr: "Inde" } },
  { code: "ID", name: { bg: "Индонезия", en: "Indonesia", de: "Indonesien", es: "Indonesia", fr: "Indonésie" } },
  { code: "IR", name: { bg: "Иран", en: "Iran", de: "Iran", es: "Irán", fr: "Iran" } },
  { code: "IQ", name: { bg: "Ирак", en: "Iraq", de: "Irak", es: "Irak", fr: "Irak" } },
  { code: "IE", name: { bg: "Ирландия", en: "Ireland", de: "Irland", es: "Irlanda", fr: "Irlande" } },
  { code: "IL", name: { bg: "Израел", en: "Israel", de: "Israel", es: "Israel", fr: "Israël" } },
  { code: "IT", name: { bg: "Италия", en: "Italy", de: "Italien", es: "Italia", fr: "Italie" } },
  { code: "JM", name: { bg: "Ямайка", en: "Jamaica", de: "Jamaika", es: "Jamaica", fr: "Jamaïque" } },
  { code: "JP", name: { bg: "Япония", en: "Japan", de: "Japan", es: "Japón", fr: "Japon" } },
  { code: "JO", name: { bg: "Йордания", en: "Jordan", de: "Jordanien", es: "Jordania", fr: "Jordanie" } },
  { code: "KZ", name: { bg: "Казахстан", en: "Kazakhstan", de: "Kasachstan", es: "Kazajistán", fr: "Kazakhstan" } },
  { code: "KE", name: { bg: "Кения", en: "Kenya", de: "Kenia", es: "Kenia", fr: "Kenya" } },
  { code: "KR", name: { bg: "Южна Корея", en: "South Korea", de: "Südkorea", es: "Corea del Sur", fr: "Corée du Sud" } },
  { code: "KW", name: { bg: "Кувейт", en: "Kuwait", de: "Kuwait", es: "Kuwait", fr: "Koweït" } },
  { code: "LV", name: { bg: "Латвия", en: "Latvia", de: "Lettland", es: "Letonia", fr: "Lettonie" } },
  { code: "LB", name: { bg: "Ливан", en: "Lebanon", de: "Libanon", es: "Líbano", fr: "Liban" } },
  { code: "LT", name: { bg: "Литва", en: "Lithuania", de: "Litauen", es: "Lituania", fr: "Lituanie" } },
  { code: "LU", name: { bg: "Люксембург", en: "Luxembourg", de: "Luxemburg", es: "Luxemburgo", fr: "Luxembourg" } },
  { code: "MK", name: { bg: "Северна Македония", en: "North Macedonia", de: "Nordmazedonien", es: "Macedonia del Norte", fr: "Macédoine du Nord" } },
  { code: "MG", name: { bg: "Мадагаскар", en: "Madagascar", de: "Madagaskar", es: "Madagascar", fr: "Madagascar" } },
  { code: "MY", name: { bg: "Малайзия", en: "Malaysia", de: "Malaysia", es: "Malasia", fr: "Malaisie" } },
  { code: "MT", name: { bg: "Малта", en: "Malta", de: "Malta", es: "Malta", fr: "Malte" } },
  { code: "MX", name: { bg: "Мексико", en: "Mexico", de: "Mexiko", es: "México", fr: "Mexique" } },
  { code: "MD", name: { bg: "Молдова", en: "Moldova", de: "Moldau", es: "Moldavia", fr: "Moldavie" } },
  { code: "MC", name: { bg: "Монако", en: "Monaco", de: "Monaco", es: "Mónaco", fr: "Monaco" } },
  { code: "MN", name: { bg: "Монголия", en: "Mongolia", de: "Mongolei", es: "Mongolia", fr: "Mongolie" } },
  { code: "ME", name: { bg: "Черна гора", en: "Montenegro", de: "Montenegro", es: "Montenegro", fr: "Monténégro" } },
  { code: "MA", name: { bg: "Мароко", en: "Morocco", de: "Marokko", es: "Marruecos", fr: "Maroc" } },
  { code: "MZ", name: { bg: "Мозамбик", en: "Mozambique", de: "Mosambik", es: "Mozambique", fr: "Mozambique" } },
  { code: "MM", name: { bg: "Мианмар", en: "Myanmar", de: "Myanmar", es: "Myanmar", fr: "Myanmar" } },
  { code: "NP", name: { bg: "Непал", en: "Nepal", de: "Nepal", es: "Nepal", fr: "Népal" } },
  { code: "NL", name: { bg: "Нидерландия", en: "Netherlands", de: "Niederlande", es: "Países Bajos", fr: "Pays-Bas" } },
  { code: "NZ", name: { bg: "Нова Зеландия", en: "New Zealand", de: "Neuseeland", es: "Nueva Zelanda", fr: "Nouvelle-Zélande" } },
  { code: "NI", name: { bg: "Никарагуа", en: "Nicaragua", de: "Nicaragua", es: "Nicaragua", fr: "Nicaragua" } },
  { code: "NG", name: { bg: "Нигерия", en: "Nigeria", de: "Nigeria", es: "Nigeria", fr: "Nigéria" } },
  { code: "NO", name: { bg: "Норвегия", en: "Norway", de: "Norwegen", es: "Noruega", fr: "Norvège" } },
  { code: "OM", name: { bg: "Оман", en: "Oman", de: "Oman", es: "Omán", fr: "Oman" } },
  { code: "PK", name: { bg: "Пакистан", en: "Pakistan", de: "Pakistan", es: "Pakistán", fr: "Pakistan" } },
  { code: "PA", name: { bg: "Панама", en: "Panama", de: "Panama", es: "Panamá", fr: "Panama" } },
  { code: "PY", name: { bg: "Парагвай", en: "Paraguay", de: "Paraguay", es: "Paraguay", fr: "Paraguay" } },
  { code: "PE", name: { bg: "Перу", en: "Peru", de: "Peru", es: "Perú", fr: "Pérou" } },
  { code: "PH", name: { bg: "Филипини", en: "Philippines", de: "Philippinen", es: "Filipinas", fr: "Philippines" } },
  { code: "PL", name: { bg: "Полша", en: "Poland", de: "Polen", es: "Polonia", fr: "Pologne" } },
  { code: "PT", name: { bg: "Португалия", en: "Portugal", de: "Portugal", es: "Portugal", fr: "Portugal" } },
  { code: "QA", name: { bg: "Катар", en: "Qatar", de: "Katar", es: "Catar", fr: "Qatar" } },
  { code: "RO", name: { bg: "Румъния", en: "Romania", de: "Rumänien", es: "Rumanía", fr: "Roumanie" } },
  { code: "RU", name: { bg: "Русия", en: "Russia", de: "Russland", es: "Rusia", fr: "Russie" } },
  { code: "SA", name: { bg: "Саудитска Арабия", en: "Saudi Arabia", de: "Saudi-Arabien", es: "Arabia Saudita", fr: "Arabie saoudite" } },
  { code: "SN", name: { bg: "Сенегал", en: "Senegal", de: "Senegal", es: "Senegal", fr: "Sénégal" } },
  { code: "RS", name: { bg: "Сърбия", en: "Serbia", de: "Serbien", es: "Serbia", fr: "Serbie" } },
  { code: "SG", name: { bg: "Сингапур", en: "Singapore", de: "Singapur", es: "Singapur", fr: "Singapour" } },
  { code: "SK", name: { bg: "Словакия", en: "Slovakia", de: "Slowakei", es: "Eslovaquia", fr: "Slovaquie" } },
  { code: "SI", name: { bg: "Словения", en: "Slovenia", de: "Slowenien", es: "Eslovenia", fr: "Slovénie" } },
  { code: "ZA", name: { bg: "Южна Африка", en: "South Africa", de: "Südafrika", es: "Sudáfrica", fr: "Afrique du Sud" } },
  { code: "ES", name: { bg: "Испания", en: "Spain", de: "Spanien", es: "España", fr: "Espagne" } },
  { code: "LK", name: { bg: "Шри Ланка", en: "Sri Lanka", de: "Sri Lanka", es: "Sri Lanka", fr: "Sri Lanka" } },
  { code: "SE", name: { bg: "Швеция", en: "Sweden", de: "Schweden", es: "Suecia", fr: "Suède" } },
  { code: "CH", name: { bg: "Швейцария", en: "Switzerland", de: "Schweiz", es: "Suiza", fr: "Suisse" } },
  { code: "TW", name: { bg: "Тайван", en: "Taiwan", de: "Taiwan", es: "Taiwán", fr: "Taïwan" } },
  { code: "TH", name: { bg: "Тайланд", en: "Thailand", de: "Thailand", es: "Tailandia", fr: "Thaïlande" } },
  { code: "TN", name: { bg: "Тунис", en: "Tunisia", de: "Tunesien", es: "Túnez", fr: "Tunisie" } },
  { code: "TR", name: { bg: "Турция", en: "Turkey", de: "Türkei", es: "Turquía", fr: "Turquie" } },
  { code: "UA", name: { bg: "Украйна", en: "Ukraine", de: "Ukraine", es: "Ucrania", fr: "Ukraine" } },
  { code: "AE", name: { bg: "ОАЕ", en: "United Arab Emirates", de: "Vereinigte Arabische Emirate", es: "Emiratos Árabes Unidos", fr: "Émirats arabes unis" } },
  { code: "GB", name: { bg: "Великобритания", en: "United Kingdom", de: "Vereinigtes Königreich", es: "Reino Unido", fr: "Royaume-Uni" } },
  { code: "US", name: { bg: "САЩ", en: "United States", de: "Vereinigte Staaten", es: "Estados Unidos", fr: "États-Unis" } },
  { code: "UY", name: { bg: "Уругвай", en: "Uruguay", de: "Uruguay", es: "Uruguay", fr: "Uruguay" } },
  { code: "UZ", name: { bg: "Узбекистан", en: "Uzbekistan", de: "Usbekistan", es: "Uzbekistán", fr: "Ouzbékistan" } },
  { code: "VE", name: { bg: "Венецуела", en: "Venezuela", de: "Venezuela", es: "Venezuela", fr: "Venezuela" } },
  { code: "VN", name: { bg: "Виетнам", en: "Vietnam", de: "Vietnam", es: "Vietnam", fr: "Viêt Nam" } },
];

export function getCountryName(country: Country, language: AppLanguage): string {
  return country.name[language] ?? country.name.en;
}

export function getCountriesSorted(language: AppLanguage): Country[] {
  return [...COUNTRIES].sort((a, b) =>
    getCountryName(a, language).localeCompare(getCountryName(b, language))
  );
}
